apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oficina

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - mailhog.yaml
  - deployment.yaml
  - hpa.yaml

# O CI sobrescreve a imagem com:
#   kustomize edit set image oficina-api=ghcr.io/<owner>/oficina-api:<tag>
images:
  - name: oficina-api
    newName: oficina-api
    newTag: latest
